### ISSUE TITLE
Test detection finds editor temp files

### ISSUE THREAD

**Issue by mjj29** [pysys-test/pysys-test#55]
**Describe the bug**
When running a pysys test which an editor has created a temporary or backup copy of the pysystest.py, pysys refuses to run the test

**To Reproduce**
Create a test case, edit the pysystest.py with vim, so that it creates a pysystest.py~ file (on windows), use pysys run

**Expected behavior**
The test runs

**Actual behaviour**
C:\Users\mjj29\git\home-automation\tests>pysys run

PYSYS FATAL ERROR: Only one test should be present per directory but found ['pysystest.py', 'pysystest.py~'] in \\?\C:\Users\mjj29\git\home-automation\tests\Devices
Traceback (most recent call last):
  File "C:\SoftwareAG\Apama\third_party\python\Lib\site-packages\pysys\launcher\console_run.py", line 398, in runTest
    args = launcher.parseArgs(args)
  File "C:\SoftwareAG\Apama\third_party\python\Lib\site-packages\pysys\launcher\console_run.py", line 382, in parseArgs
    descriptors = createDescriptors(self.arguments, self.type, self.includes, self.excludes, self.trace, self.workingDir,
  File "C:\SoftwareAG\Apama\third_party\python\Lib\site-packages\pysys\launcher\__init__.py", line 73, in createDescriptors
    descriptors = loadDescriptors(dir=dir)
  File "C:\SoftwareAG\Apama\third_party\python\Lib\site-packages\pysys\launcher\__init__.py", line 46, in loadDescriptors
    return loader.loadDescriptors(dir)
  File "C:\SoftwareAG\Apama\third_party\python\Lib\site-packages\pysys\config\descriptor.py", line 1259, in loadDescriptors
    if len(intersection) > 1: raise Exception('Only one test should be present per directory but found %s in %s'%(intersection, root))
Exception: Only one test should be present per directory but found ['pysystest.py', 'pysystest.py~'] in \\?\C:\Users\mjj29\git\home-automation\tests\Devices

**Affected version(s)**
PySys System Test Framework (version 2.0 on Python 3.9.5)
Windows 10

**Comment by ben-spiller** [comment]
Probably we should exclude *~ and *.swp, and check for other common ones from editors maybe using https://github.com/github/gitignore for inspiration. Also good to have an env var to allow local (per-machine/user) additions
